### ISSUE TITLE
 Internal Server Error

### ISSUE THREAD

**Issue by EslamAsHhraf** [m2b3/SciCommons-frontend#1]
![image](https://github.com/m2b3/SciCommons-frontend/assets/71986226/1aad4b52-3404-405e-a59f-949818c0c24b)

**Comment by JyothiSwaroopReddy07** [comment]
did you create .env file before running backend?

**Comment by EslamAsHhraf** [comment]
@JyothiSwaroopReddy07 No because I think that api is deployed isn't it?

**Comment by JyothiSwaroopReddy07** [comment]
We are not yet read for registrations.
