### ISSUE TITLE
Why to display join community button for that particular community admin itself.

### ISSUE THREAD

**Issue by rajubugude** [m2b3/SciCommons-frontend#30]
It is pretty staright forward , a particular user after creating his/her own community why to join or display join community button in his profile under the https://www.scicommons.org/communities.
Here are the screenshots of the issue .
<img width="1454" alt="Screenshot 2024-03-18 at 10 47 49 PM" src="https://github.com/m2b3/SciCommons-frontend/assets/88735632/5109b481-e3cc-48b1-9182-7aa2846d7f3b">
<img width="1495" alt="Screenshot 2024-03-18 at 10 48 34 PM" src="https://github.com/m2b3/SciCommons-frontend/assets/88735632/ccd5db9b-0db4-4065-9d28-654532c18f11">
<img width="1497" alt="Screenshot 2024-03-18 at 10 48 43 PM" src="https://github.com/m2b3/SciCommons-frontend/assets/88735632/b70bf9cc-82bf-402c-abfb-82d922b6f0ab">
<img width="1489" alt="Screenshot 2024-03-18 at 10 48 58 PM" src="https://github.com/m2b3/SciCommons-frontend/assets/88735632/781eb907-b167-4049-8632-b2a51c8f98bc">

**Comment by JyothiSwaroopReddy07** [comment]
https://github.com/m2b3/SciCommons-frontend/pull/31

resolved the issue.
